// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuyK0gsU6P1iH2zBfLTEKgbjEZx3z4k90',
    appId: '1:264918662033:web:3029cf068709e859307830',
    messagingSenderId: '264918662033',
    projectId: 'b2bproject-b2c91',
    authDomain: 'b2bproject-b2c91.firebaseapp.com',
    storageBucket: 'b2bproject-b2c91.firebasestorage.app',
    measurementId: 'G-QV1XRTFJBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnKfImTiZ5b0OMASLCGzlzr8FNGDNtnI8',
    appId: '1:264918662033:android:366957959051b680307830',
    messagingSenderId: '264918662033',
    projectId: 'b2bproject-b2c91',
    storageBucket: 'b2bproject-b2c91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAziz6tahCWlTEyAnr4LfKJmxAP71Cjp6c',
    appId: '1:264918662033:ios:e8c1e1059b191db2307830',
    messagingSenderId: '264918662033',
    projectId: 'b2bproject-b2c91',
    storageBucket: 'b2bproject-b2c91.firebasestorage.app',
    androidClientId: '264918662033-ghjnv5o80vqhcke252pj89b10dok9k12.apps.googleusercontent.com',
    iosClientId: '264918662033-l96flfornv0mg9r1s0v4fr4bog2ssn7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.khyateB2b',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAziz6tahCWlTEyAnr4LfKJmxAP71Cjp6c',
    appId: '1:264918662033:ios:e8c1e1059b191db2307830',
    messagingSenderId: '264918662033',
    projectId: 'b2bproject-b2c91',
    storageBucket: 'b2bproject-b2c91.firebasestorage.app',
    androidClientId: '264918662033-ghjnv5o80vqhcke252pj89b10dok9k12.apps.googleusercontent.com',
    iosClientId: '264918662033-l96flfornv0mg9r1s0v4fr4bog2ssn7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.khyateB2b',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuyK0gsU6P1iH2zBfLTEKgbjEZx3z4k90',
    appId: '1:264918662033:web:d1e56f3080af673d307830',
    messagingSenderId: '264918662033',
    projectId: 'b2bproject-b2c91',
    authDomain: 'b2bproject-b2c91.firebaseapp.com',
    storageBucket: 'b2bproject-b2c91.firebasestorage.app',
    measurementId: 'G-CRSPK4YJD2',
  );
}
